### ISSUE TITLE
Turn on code analysis for the solution (all projects)

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/command-line-api#16]
See https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/

**Tasks:**
- [ ] Discuss/determine ruleset and create solution ruleset
- [ ] Add solution ruleset via link to each project
- [ ] Turn on code analysis for all projects
- [ ] Ensure rule violation appears as error (turn on warnings as errors)
