### ISSUE TITLE
Tracking issue for Error changes

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/command-line-api#2375]
## For parsing

- [ ] Approve Error proposal
- [ ] Change `ParseError` name to `CliError`
- [ ] Create `CliError` and `CliDiagnosticDescriptor` 
- [ ] Replace all error creation with 'CliError'
- [ ] Comment out code for argument required, option and command (*)
- [ ] Comment out `ArgumentArity.Validate` and its call in `ArgumentResult` and `CommandResult` after checking the proposal's explanation of maximum arity and token limit reached (**)
- [ ] Change `SymbolTree.AddError` to take a `CliError` and associated fixes
- [ ] Collect `SymbolTree` errors into `ParseResult.Errors`
- [ ] Update existing tests to use `CliError`
- [ ] Add any additional tests deemed necessary

(*) This is a validation check that does not need to affect further parsing. In its current form, it also blocks making `ParseResult` sparse.

(**) See Arity section of Error proposal

## For ErrorReporting subsystem

TBD
